# Generated by Django 4.2.7 on 2023-12-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olxuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
