# Generated by Django 4.2.7 on 2023-12-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_olxuser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olxuser',
            name='is_approved',
            field=models.CharField(choices=[(0, 'Stasis'), (1, 'Approved'), (2, 'Rejected')], default=0, max_length=50),
        ),
    ]
