# Generated by Django 4.2.7 on 2023-12-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_olxuser_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olxuser',
            name='is_approved',
            field=models.IntegerField(choices=[(0, 'Stasis'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
