# Generated by Django 4.2.7 on 2023-12-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0005_alter_olxuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olxuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='olx_user_permissions', to='auth.permission'),
        ),
    ]
